In [1]:
import pandas as pd

In [3]:
data = pd.read_csv(r'C:\Users\hi\Downloads\Heart_diseases_predicter\heart.csv')
data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [4]:
data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [12]:
data.duplicated().sum()

np.int64(723)

In [13]:
data[data.duplicated()].head(5)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
15,34,0,1,118,210,0,1,192,0,0.7,2,0,2,1
31,50,0,1,120,244,0,1,162,0,1.1,2,0,2,1
43,46,1,0,120,249,0,0,144,0,0.8,2,0,3,0
55,55,1,0,140,217,0,1,111,1,5.6,0,0,3,0
61,66,0,2,146,278,0,0,152,0,0.0,1,1,2,1

In [14]:
data[data.duplicated(keep=False)].sort_values(
    by=list(data.columns)
).head(20)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
60,29,1,1,130,204,0,0,202,0,0.0,2,0,2,1
64,29,1,1,130,204,0,0,202,0,0.0,2,0,2,1
118,29,1,1,130,204,0,0,202,0,0.0,2,0,2,1
668,29,1,1,130,204,0,0,202,0,0.0,2,0,2,1
12,34,0,1,118,210,0,1,192,0,0.7,2,0,2,1
15,34,0,1,118,210,0,1,192,0,0.7,2,0,2,1
779,34,0,1,118,210,0,1,192,0,0.7,2,0,2,1
143,34,1,3,118,182,0,0,174,0,0.0,2,0,2,1
201,34,1,3,118,182,0,0,174,0,0.0,2,0,2,1
572,34,1,3,118,182,0,0,174,0,0.0,2,0,2,1
256,35,0,0,138,183,0,1,182,0,1.4,2,0,2,1
501,35,0,0,138,183,0,1,182,0,1.4,2,0,2,1
841,35,0,0,138,183,0,1,182,0,1.4,2,0,2,1
846,35,0,0,138,183,0,1,182,0,1.4,2,0,2,1
254,35,1,0,120,198,0,1,130,1,1.6,1,0,3,0
701,35,1,0,120,198,0,1,130,1,1.6,1,0,3,0
711,35,1,0,120,198,0,1,130,1,1.6,1,0,3,0
912,35,1,0,120,198,0,1,130,1,1.6,1,0,3,0
384,35,1,0,126,282,0,0,156,1,0.0,2,0,3,0
695,35,1,0,126,282,0,0,156,1,0.0,2,0,3,0

In [15]:
data.drop_duplicates(inplace=True)

In [17]:
data.shape

(302, 14)

In [18]:
data1 = data

In [19]:
data1.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [20]:
data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [21]:
data1["high_chol"] = (data1["chol"] >= 240).astype(int)

In [22]:
data1["high_bp"] = (data1["trestbps"] >= 140).astype(int)
data1["age_risk"] = (data1["age"] >= 60).astype(int)
data1["risk_score"] = (
    data1["high_chol"] +
    data1["high_bp"] +
    data1["age_risk"] +
    data1["exang"]
)

In [23]:
data1.shape

(302, 18)

In [24]:
data.shape

(302, 18)

In [25]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 302 entries, 0 to 878
Data columns (total 18 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   age         302 non-null    int64
 1   sex         302 non-null    int64
 2   cp          302 non-null    int64
 3   trestbps    302 non-null    int64
 4   chol        302 non-null    int64
 5   fbs         302 non-null    int64
 6   restecg     302 non-null    int64
 7   thalach     302 non-null    int64
 8   exang       302 non-null    int64
 9   oldpeak     302 non-null    float64
 10  slope       302 non-null    int64
 11  ca          302 non-null    int64
 12  thal        302 non-null    int64
 13  target      302 non-null    int64
 14  high_chol   302 non-null    int64
 15  high_bp     302 non-null    int64
 16  age_risk    302 non-null    int64
 17  risk_score  302 non-null    int64
dtypes: float64(1), int64(17)
memory usage: 44.8 KB

In [26]:
data.drop(
    ["high_chol", "high_bp", "age_risk", "risk_score"],
    axis=1,
    inplace=True
)

In [27]:
data.shape

(302, 14)

In [28]:
data1.shape

(302, 14)

In [29]:
data1=data.copy()

In [30]:
data1["high_chol"] = (data1["chol"] >= 240).astype(int)
data1["high_bp"] = (data1["trestbps"] >= 140).astype(int)
data1["age_risk"] = (data1["age"] >= 60).astype(int)
data1["risk_score"] = (
    data1["high_chol"] +
    data1["high_bp"] +
    data1["age_risk"] +
    data1["exang"]
)

In [32]:
data1.shape

(302, 18)

In [33]:
data.shape

(302, 14)

In [34]:
X= data.drop("target", axis = 1)
y = data["target"]

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
x_train, x_test, y_train, y_test = train_test_split(X,y , test_size= 0.2, random_state=42)

In [38]:
!pip install xgboost

Defaulting to user installation because normal site-packages is not writeable
Collecting xgboost
  Using cached xgboost-3.2.0-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in c:\users\hi\appdata\roaming\python\python311\site-packages (from xgboost) (2.3.5)
Requirement already satisfied: scipy in c:\users\hi\appdata\roaming\python\python311\site-packages (from xgboost) (1.16.3)
Using cached xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
Installing collected packages: xgboost
Successfully installed xgboost-3.2.0

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [39]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score

model = XGBClassifier()

model.fit(x_train, y_train)

y_pred = model.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.8032786885245902

In [58]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix



# Create Model
rf_model = RandomForestClassifier(
    n_estimators=100,
    max_depth=5,
    random_state=42
)

# Train Model
rf_model.fit(x_train, y_train)

# Predictions
y_pred = rf_model.predict(x_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Classification Report
print(classification_report(y_test, y_pred))

# Confusion Matrix
print(confusion_matrix(y_test, y_pred))

new_data = pd.read_csv(r'C:\Users\hi\Downloads\Heart_diseases_predicter\heart_test_input.csv')

predictions = rf_model.predict(new_data)

print(predictions)

Accuracy: 0.8360655737704918
              precision    recall  f1-score   support

           0       0.89      0.78      0.83        32
           1       0.79      0.90      0.84        29

    accuracy                           0.84        61
   macro avg       0.84      0.84      0.84        61
weighted avg       0.84      0.84      0.84        61

[[25  7]
 [ 3 26]]
[1 1 0 1 0 1 0 1 0 1 0 1 0 1 0]

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

# Train Model
model.fit(x_train, y_train)

# Predictions
y_pred = model.predict(x_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Classification Report
print(classification_report(y_test, y_pred))

# Confusion Matrix
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.8032786885245902
              precision    recall  f1-score   support

           0       0.88      0.72      0.79        32
           1       0.74      0.90      0.81        29

    accuracy                           0.80        61
   macro avg       0.81      0.81      0.80        61
weighted avg       0.82      0.80      0.80        61

[[23  9]
 [ 3 26]]

C:\Users\hi\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [51]:
import mlflow
import mlflow.sklearn



mlflow.set_experiment("Heart_Disease_Project")

models = {
    "LogisticRegression": LogisticRegression(max_iter=1000),
    "RandomForest": RandomForestClassifier(
        n_estimators=100,
        random_state=42
    ),
    "XGBoost": XGBClassifier(
        random_state=42
    )
}

for model_name, model in models.items():

    with mlflow.start_run(run_name=model_name):

        model.fit(x_train, y_train)

        y_pred = model.predict(x_test)

        accuracy = accuracy_score(
            y_test,
            y_pred
        )

        mlflow.log_metric(
            "accuracy",
            accuracy
        )

        mlflow.sklearn.log_model(
            model,
            model_name
        )

        print(
            f"{model_name}: {accuracy}"
        )

C:\Users\hi\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
2026/07/01 16:07:28 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/07/01 16:07:28 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

LogisticRegression: 0.8032786885245902

2026/07/01 16:07:53 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/07/01 16:07:53 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

RandomForest: 0.8360655737704918

2026/07/01 16:08:02 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/07/01 16:08:02 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

XGBoost: 0.8032786885245902

In [ ]:
import mlflow
import mlflow.sklearn


models = {
    "LogisticRegression": LogisticRegression(max_iter=1000),
    "RandomForest": RandomForestClassifier(random_state=42),
    "XGBoost": XGBClassifier(random_state=42)
}

for model_name, model in models.items():

    with mlflow.start_run(run_name=model_name):

        model.fit(x_train, y_train)

        y_pred = model.predict(x_test)

        accuracy = accuracy_score(y_test, y_pred)

        mlflow.log_metric("accuracy", accuracy)

        mlflow.sklearn.log_model(model, model_name)

        print(model_name, accuracy)

C:\Users\hi\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
2026/07/01 16:15:33 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/07/01 16:15:33 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

LogisticRegression 0.8032786885245902

2026/07/01 16:15:56 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/07/01 16:15:56 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

RandomForest 0.8360655737704918

2026/07/01 16:16:05 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/07/01 16:16:05 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

XGBoost 0.8032786885245902

In [55]:
import mlflow
import mlflow.sklearn

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

from sklearn.metrics import accuracy_score

models = {
    "LogisticRegression": LogisticRegression(max_iter=1000),
    "RandomForest": RandomForestClassifier(random_state=42),
    "XGBoost": XGBClassifier(random_state=42)
}

for model_name, model in models.items():

    with mlflow.start_run(run_name=model_name):

        model.fit(x_train, y_train)

        y_pred = model.predict(x_test)

        accuracy = accuracy_score(y_test, y_pred)

        mlflow.log_metric("accuracy", accuracy)

        mlflow.sklearn.log_model(model, model_name)

        print(model_name, accuracy)

C:\Users\hi\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
2026/07/01 16:36:11 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/07/01 16:36:11 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

LogisticRegression 0.8032786885245902

2026/07/01 16:36:30 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/07/01 16:36:31 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

RandomForest 0.8360655737704918

2026/07/01 16:36:43 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/07/01 16:36:43 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

XGBoost 0.8032786885245902

In [56]:
import mlflow

with mlflow.start_run(run_name="Test_Run"):
    mlflow.log_param("model", "test")
    mlflow.log_metric("accuracy", 0.95)

print("Run logged successfully")

Run logged successfully

In [59]:
import joblib

joblib.dump(rf_model, "model.pkl")

['model.pkl']